POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Adrian Sanchez",
  "dateOfBirth": "1995-05-20",
  "ssn": "200595-123A",
  "gender": "male",
  "occupation": "Developer"
}

###

POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Adrian Sanchez",
  "dateOfBirth": "1995-05-20",
  "ssn": "200595-123A",
  "gender": "male",
  "occupation": "Developer"
}

### Gender male
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Test Male",
  "dateOfBirth": "1990-01-01",
  "ssn": "010190-123A",
  "gender": "male",
  "occupation": "Developer"
}

### Gender female
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Test Female",
  "dateOfBirth": "1990-01-01",
  "ssn": "010190-123B",
  "gender": "female",
  "occupation": "Developer"
}

### Gender other
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Test Other",
  "dateOfBirth": "1990-01-01",
  "ssn": "010190-123C",
  "gender": "other",
  "occupation": "Developer"
}


### Gender incorrecto
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Paciente Incorrecto",
  "dateOfBirth": "1990-01-01",
  "ssn": "010190-123D",
  "gender": "banana",
  "occupation": "Developer"
}

###

POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2026-08-10",
  "type": "HealthCheck",
  "specialist": "Dr House",
  "description": "Annual health check",
  "healthCheckRating": 0,
  "diagnosisCodes": ["Z00.0"]
}

###

POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2026-08-10",
  "type": "HealthCheck",
  "specialist": "Dr. House",
  "description": "Annual health check"
}